export type BadgeTier = {
  level: number;
  name: string;
  title: string;
  rarity: "Common" | "Uncommon" | "Rare" | "Epic" | "Mythic" | "Legendary";
  requirement: string;
  /** metal frame: [light, mid, dark] */
  metal: [string, string, string];
  /** inner gem / plate: [light, mid, dark] */
  gem: [string, string, string];
  glow: string;
  ornament: 0 | 1 | 2 | 3 | 4;
  crown: boolean;
  wings: boolean;
  gems: number;
  unlocked: boolean;
};

export const BADGE_TIERS: BadgeTier[] = [
  {
    level: 1,
    name: "Bronze",
    title: "First Step",
    rarity: "Common",
    requirement: "Complete your first mining session",
    metal: ["#e0a877", "#b3703c", "#6d3f1d"],
    gem: ["#f0c39a", "#c07a44", "#5c3418"],
    glow: "#c98a52",
    ornament: 0,
    crown: false,
    wings: false,
    gems: 0,
    unlocked: true,
  },
  {
    level: 2,
    name: "Silver",
    title: "Rising Star",
    rarity: "Common",
    requirement: "Earn 500 VEs in total",
    metal: ["#f4f6fa", "#b9c1cf", "#6d7686"],
    gem: ["#ffffff", "#cdd5e2", "#69717f"],
    glow: "#c9d2e0",
    ornament: 1,
    crown: false,
    wings: false,
    gems: 0,
    unlocked: true,
  },
  {
    level: 3,
    name: "Gold",
    title: "Reward Hunter",
    rarity: "Uncommon",
    requirement: "Mine on 7 consecutive days",
    metal: ["#ffe9ac", "#e0b95a", "#8a5f16"],
    gem: ["#fff3c9", "#eec25c", "#8a6218"],
    glow: "#e8bd5c",
    ornament: 1,
    crown: false,
    wings: false,
    gems: 1,
    unlocked: true,
  },
  {
    level: 4,
    name: "Platinum",
    title: "Elite Earner",
    rarity: "Uncommon",
    requirement: "Reach 5,000 VEs mined",
    metal: ["#f7fbff", "#c3ccd9", "#7c8593"],
    gem: ["#e8f1fb", "#a8b8ce", "#5d6a7d"],
    glow: "#cfdaea",
    ornament: 2,
    crown: false,
    wings: false,
    gems: 1,
    unlocked: true,
  },
  {
    level: 5,
    name: "Diamond",
    title: "High Achiever",
    rarity: "Rare",
    requirement: "Complete 100 mining sessions",
    metal: ["#f2f7ff", "#bcc9de", "#6f7b8f"],
    gem: ["#eaf6ff", "#9cc9ea", "#3f6b8c"],
    glow: "#9dcdef",
    ornament: 2,
    crown: false,
    wings: false,
    gems: 2,
    unlocked: false,
  },
  {
    level: 6,
    name: "Emerald",
    title: "Reward Master",
    rarity: "Rare",
    requirement: "Convert 10,000 SVEs to VEs",
    metal: ["#ffeeb8", "#d8ae5a", "#7d5a1a"],
    gem: ["#bfe6cd", "#4f9a72", "#1e4735"],
    glow: "#5ea885",
    ornament: 3,
    crown: false,
    wings: false,
    gems: 2,
    unlocked: false,
  },
  {
    level: 7,
    name: "Sapphire",
    title: "Top Performer",
    rarity: "Epic",
    requirement: "Hold a 30-day mining streak",
    metal: ["#f4f8ff", "#c2cee3", "#6f7c93"],
    gem: ["#bcd4f2", "#3f6cb8", "#1a2f5e"],
    glow: "#4f7fc9",
    ornament: 3,
    crown: false,
    wings: false,
    gems: 3,
    unlocked: false,
  },
  {
    level: 8,
    name: "Ruby",
    title: "Elite",
    rarity: "Epic",
    requirement: "Mine 50,000 VEs lifetime",
    metal: ["#ffe9ae", "#d6a94f", "#7a5514"],
    gem: ["#eeb4b4", "#a52e3f", "#4c101c"],
    glow: "#b03a49",
    ornament: 4,
    crown: false,
    wings: false,
    gems: 3,
    unlocked: false,
  },
  {
    level: 9,
    name: "Master",
    title: "Master Achiever",
    rarity: "Mythic",
    requirement: "Rank top 1% of miners for a season",
    metal: ["#fff2c4", "#dcae4d", "#7c5511"],
    gem: ["#e3d3ff", "#7b5cc4", "#2f2158"],
    glow: "#9d7fe0",
    ornament: 4,
    crown: true,
    wings: false,
    gems: 4,
    unlocked: false,
  },
  {
    level: 10,
    name: "Legend",
    title: "VELOOP Legend",
    rarity: "Legendary",
    requirement: "Complete every milestone in the reward journey",
    metal: ["#fff6d2", "#e8bf5c", "#8a6013"],
    gem: ["#fff0bf", "#e0a52f", "#6a3f0c"],
    glow: "#f0c765",
    ornament: 4,
    crown: true,
    wings: true,
    gems: 5,
    unlocked: false,
  },
];
